
# STA141B Discussion 3

Chi Po Choi cpchoi@ucdavis.edu



# Online Jupyter Notebooks

#### Microsoft Azure Notebooks

https://notebooks.azure.com/

#### Google Colaboratory

https://colab.research.google.com/



# Coding exercises:

- 
  https://projecteuler.net <br>
  Register an account and solve the problems with Python (or any programming language of your choice, as long as you can solve the problems with it) <br>
  Problem 19: Counting Sundays
  https://projecteuler.net/problem=19

- Online Judge for coding problems (actually technical interview preparation...): <br>
  https://leetcode.com/ <br>
  https://www.hackerrank.com/ <br>
  etc......



# Ig Nobel Prize 2018

LITERATURE PRIZE [AUSTRALIA, EL SALVADOR, UK] — Thea Blackler, Rafael Gomez, Vesna Popovic and M. Helen Thompson, for documenting that most people who use complicated products do not read the instruction manual.

REFERENCE: "Life Is Too Short to RTFM: How Users Relate to Documentation and Excess Features in Consumer Products," Alethea L. Blackler, Rafael Gomez, Vesna Popovic and M. Helen Thompson, Interacting With Computers, vol. 28, no. 1, 2014, pp. 27-46.

https://academic.oup.com/iwc/article/28/1/27/2363584

#### Python Tutorial

https://docs.python.org/3/tutorial/

#### Python 3.6 Manual

https://docs.python.org/3.6/

#### NumPy User Guide

https://docs.scipy.org/doc/numpy-1.15.1/user/index.html#user

#### NumPy Manual

https://docs.scipy.org/doc/numpy-1.15.1/reference/


# How to make your Python codes look better

#### Style Guide for Python Code

https://www.python.org/dev/peps/pep-0008/

Comments: https://www.python.org/dev/peps/pep-0008/#comments

Naming conventions: https://www.python.org/dev/peps/pep-0008/#naming-conventions

Maximum line length: https://www.python.org/dev/peps/pep-0008/#maximum-line-length

#### Docstring Conventions

https://www.python.org/dev/peps/pep-0257/


#### Example NumPy Style Python Docstrings

https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html


# Homework 2

#### Useful functions for NumPy array

https://docs.scipy.org/doc/numpy-1.15.1/reference/routines.array-manipulation.html

#### Linear Algebra in NumPy

https://docs.scipy.org/doc/numpy-1.15.1/reference/routines.linalg.html

#### FFT in NumPy

https://docs.scipy.org/doc/numpy-1.15.1/reference/routines.fft.html

#### Documentation

- Use docstring to provide general descriptions for your functions. What is the purposes of your functions? How to use your functions (a.k.a what are the inputs and outputs exactly)?

- Use comments when it helps to understand your codes. On the other hands, concise and self-explanatory codes are better than lengthly comments. <br>
  There are some good guidelines in the below tutorial: <br>
  https://www.digitalocean.com/community/tutorials/how-to-write-comments-in-python-3





#### NumPy SVD

https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.linalg.svd.html#numpy.linalg.svd



Math behind the scenes

https://en.wikipedia.org/wiki/Singular_value_decomposition#Low-rank_matrix_approximation



In [10]:
import numpy as np
np.set_printoptions(precision=2, sign = ' ', suppress=True) # Better display format for lecture

In [11]:
x = np.array(
    [[0.0, 0.0, 1.0, 1.0],
     [0.0, 1.0, 1.0, 1.0],
     [1.0, 2.0, 2.0, 0.0],
     [0.0, 1.0, 1.0, 0.0],
     [0.0, 1.0, 0.0, 0.0]]
)

u, d, vt = np.linalg.svd(x)
print("u")
print(u)
print("d")
print(d)
print("v^T")
print(vt)

u
[[-0.23 -0.75 -0.22  0.01  0.58]
 [-0.41 -0.47  0.51 -0.16 -0.58]
 [-0.78  0.35 -0.41 -0.31  0.  ]
 [-0.36  0.1   0.09  0.92  0.  ]
 [-0.18  0.29  0.72 -0.17  0.58]]
d
[ 3.74  1.47  0.83  0.38]
v^T
[[-0.21 -0.67 -0.69 -0.17]
 [ 0.24  0.42 -0.28 -0.83]
 [-0.49  0.6  -0.53  0.35]
 [-0.81 -0.06  0.41 -0.41]]


$\ X = UDV^T = d_1 u_1 v_1^T + \ldots + d_m u_m v_m^T\ $

In [12]:
w1 = d[0]*np.matmul(u[:,0:1], vt[0:1,:])
w2 = d[1]*np.matmul(u[:,1:2], vt[1:2,:])
w3 = d[2]*np.matmul(u[:,2:3], vt[2:3,:])
w4 = d[3]*np.matmul(u[:,3:4], vt[3:4,:])

In [13]:
print(w1+w2+w3+w4)

[[ 0. -0.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 1.  2.  2. -0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  0.  0.]]


In [14]:
print(w1+w2+w3)

[[ 0.    0.    1.    1.  ]
 [-0.05  1.    1.03  0.97]
 [ 0.91  1.99  2.05 -0.05]
 [ 0.28  1.02  0.86  0.14]
 [-0.05  1.    0.03 -0.03]]


In [15]:
np.linalg.norm((w1+w2+w3) - x)

0.3772518430252185

In [16]:
print(w1+w2)

[[-0.09  0.11  0.9   1.06]
 [ 0.16  0.74  1.25  0.83]
 [ 0.74  2.2   1.87  0.07]
 [ 0.32  0.98  0.9   0.12]
 [ 0.24  0.63  0.34 -0.23]]


In [17]:
np.linalg.norm((w1+w2) - x)

0.914322401817276

In [22]:
D = np.pad(np.diag(d), [(0, 1), (0,0)], mode='constant')
print(D)

[[ 3.74  0.    0.    0.  ]
 [ 0.    1.47  0.    0.  ]
 [ 0.    0.    0.83  0.  ]
 [ 0.    0.    0.    0.38]
 [ 0.    0.    0.    0.  ]]


In [28]:
np.matmul(np.matmul(u, D), vt)

array([[ 0., -0.,  1.,  1.],
       [ 0.,  1.,  1.,  1.],
       [ 1.,  2.,  2., -0.],
       [ 0.,  1.,  1.,  0.],
       [-0.,  1.,  0.,  0.]])

In [29]:
u @ D @ vt

array([[ 0., -0.,  1.,  1.],
       [ 0.,  1.,  1.,  1.],
       [ 1.,  2.,  2., -0.],
       [ 0.,  1.,  1.,  0.],
       [-0.,  1.,  0.,  0.]])


FFT in NumPy
https://docs.scipy.org/doc/numpy-1.15.1/reference/routines.fft.html

In [245]:
x = np.array(
    [[0.0, 0.0, 1.0, 1.0],
     [0.0, 1.0, 1.0, 1.0],
     [1.0, 2.0, 2.0, 0.0],
     [0.0, 1.0, 1.0, 0.0],
     [0.0, 1.0, 0.0, 0.0],
     [0.0, 1.0, 0.0, 0.0]]
)

x_coef = np.fft.rfft2(x)
print(x_coef)

[[14.  +0.j   -4.  -4.j   -2.  +0.j  ]
 [-1.  -5.2j   0.  +4.73j -1.  -1.73j]
 [-1.  +1.73j  0.73+2.j    1.  +1.73j]
 [ 2.  +0.j    0.  -0.j    2.  +0.j  ]
 [-1.  -1.73j -2.73+2.j    1.  -1.73j]
 [-1.  +5.2j   0.  +1.27j -1.  +1.73j]]


In [270]:
x_back = np.fft.irfft2(x_coef, x.shape)
print(x_back)

[[ 0.  0.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 1.  2.  2.  0.]
 [ 0.  1.  1.  0.]
 [ 0.  1.  0.  0.]
 [-0.  1.  0.  0.]]


In [248]:
x_coef_test1 = x_coef.copy()
x_coef_test1[:,2] = 0.0
x_test1 = np.fft.irfft2(x_coef_test1, x.shape)
print("x_coef_test1")
print(x_coef_test1)
print("x_test1")
print(x_test1)

x_coef_test1
[[14.  +0.j   -4.  -4.j    0.  +0.j  ]
 [-1.  -5.2j   0.  +4.73j  0.  +0.j  ]
 [-1.  +1.73j  0.73+2.j    0.  +0.j  ]
 [ 2.  +0.j    0.  -0.j    0.  +0.j  ]
 [-1.  -1.73j -2.73+2.j    0.  +0.j  ]
 [-1.  +5.2j   0.  +1.27j  0.  +0.j  ]]
x_test1
[[ 0.    0.    1.    1.  ]
 [ 0.25  0.75  1.25  0.75]
 [ 0.75  2.25  1.75  0.25]
 [ 0.    1.    1.    0.  ]
 [ 0.25  0.75  0.25 -0.25]
 [ 0.25  0.75  0.25 -0.25]]


In [249]:
x_coef_test2 = x_coef.copy()
x_coef_test2[:,2] = 0.0
x_coef_test2[3,:] = 0.0
x_test2 = np.fft.irfft2(x_coef_test2, x.shape)
print("x_coef_test2")
print(x_coef_test2)
print("x_test2")
print(x_test2)

x_coef_test2
[[14.  +0.j   -4.  -4.j    0.  +0.j  ]
 [-1.  -5.2j   0.  +4.73j  0.  +0.j  ]
 [-1.  +1.73j  0.73+2.j    0.  +0.j  ]
 [ 0.  +0.j    0.  +0.j    0.  +0.j  ]
 [-1.  -1.73j -2.73+2.j    0.  +0.j  ]
 [-1.  +5.2j   0.  +1.27j  0.  +0.j  ]]
x_test2
[[-0.08 -0.08  0.92  0.92]
 [ 0.33  0.83  1.33  0.83]
 [ 0.67  2.17  1.67  0.17]
 [ 0.08  1.08  1.08  0.08]
 [ 0.17  0.67  0.17 -0.33]
 [ 0.33  0.83  0.33 -0.17]]


Math behind the scenes

https://en.wikipedia.org/wiki/Discrete_Fourier_transform
